version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      medusa:
        patterns:
          - "react*"
          - "eslint*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "react*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint*"
        update-types: ["version-update:semver-major"]